// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_hFWPQBt_7-NIK7QlXL80QlIgNxKDEGo',
    appId: '1:606277844153:web:ef2bf86c3ad2357112ef68',
    messagingSenderId: '606277844153',
    projectId: 'blogapp-final-project',
    authDomain: 'blogapp-final-project.firebaseapp.com',
    storageBucket: 'blogapp-final-project.appspot.com',
    measurementId: 'G-67YNNYBBC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqBtnpRimWw7BR5JVK1EGA9JSI85GHBS4',
    appId: '1:606277844153:android:726b85e22ef8582e12ef68',
    messagingSenderId: '606277844153',
    projectId: 'blogapp-final-project',
    storageBucket: 'blogapp-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZSTMw7czl0KvHztnVmmC4s2xV7eIXJEQ',
    appId: '1:606277844153:ios:9932dd1be5cd7cd112ef68',
    messagingSenderId: '606277844153',
    projectId: 'blogapp-final-project',
    storageBucket: 'blogapp-final-project.appspot.com',
    iosClientId: '606277844153-0qgb0mqvb9c5erhjs373ngml2o8u10po.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZSTMw7czl0KvHztnVmmC4s2xV7eIXJEQ',
    appId: '1:606277844153:ios:ecc0b886520cc20412ef68',
    messagingSenderId: '606277844153',
    projectId: 'blogapp-final-project',
    storageBucket: 'blogapp-final-project.appspot.com',
    iosClientId: '606277844153-j07k2dbdpbjmv11doumj6hnfscmu4ch6.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectBlogApp.RunnerTests',
  );
}
